/// Flutter icons Network
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Network
///      fonts:
///       - asset: fonts/Network.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Network {
  Network._();

  static const _kFontFam = 'Network';
  static const String? _kFontPkg = null;

  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electric = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tunesvg = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
